spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp      
 
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3308/db_irs
  jpa:
      show-sql: true
      hibernate:
          ddl-auto: update
        
      properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
server:
  servlet.context-path: /InfyGoBoot
  port: 8080
  
  
logging:
  file: Errorlog.log
  level:
    root: info
    com.infoys.ars: info
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"



  
    